export default function Header() {
  return (
    <header className="fold mt-12">
    {/* just for alignment */}
    <div className="sidebar" aria-hidden></div>

    <div className="content">
      {/* <img src="static/images/logo.png" height="120" width="120" className="mb-8" /> */}
      <h1 className="uppercase font-extrabold text-3xl md:text-4xl">XIRR calculator</h1>
      <h2 className="text-gray-400 font-medium mb-6">XIRR is the annual rate of return of generated by your portfolio</h2>
    </div>
  </header>
  );
}
